[[main]]
  identifier = "lodz"
  name = "Łódź"
  url = "lodz"
  weight = 1

[[main]]
  identifier = "katowice"
  name = "Katowice"
  url = "katowice"
  weight = 2

[[main]]
  identifier = "archive"
  name = "Archiwum"
  url = "archive"
  weight = 3
