[[main]]
  identifier = "p-tech"
  name = "P-TECH Program"
  url = "p-tech"
  weight = 1

[[main]]
  identifier = "lodz"
  name = "Lodz"
  url = "lodz"
  weight = 2

[[main]]
  identifier = "katowice"
  name = "Katowice"
  url = "katowice"
  weight = 3

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 4
