[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.111.3"

[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Access-Control-Allow-Origin = "https://p-tech-site.netlify.app"
      Content-Security-Policy = "base-uri 'self';  default-src 'self';  style-src 'report-sample' 'self' 'unsafe-inline' https://fonts.googleapis.com/; script-src 'report-sample' 'self' https://p-tech-site.netlify.app 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' 'sha256-o1wxtetquxyOuJoFaUFEb0G0Vilqh4QVpQfBavWBvM0=' 'sha256-o1wxtetquxyOuJoFaUFEb0G0Vilqh4QVpQfBavWBvM0=' 'sha256-0aYDHNJCU98aIpr7QTA1FPm/Ha6TVIkdowTUu2cx2Ks=' 'sha256-CJG5mNzuoX9Ni31/WJHwCg3Va2kMDT6/rUluZKAT3Z4=' 'sha256-DlH8gL38moP9pEFraWXEsuqZAagYARXD039CiDWKO+Y=' 'sha256-OeT4ggVXi2CIkxbO7xvGvBDKJ07xU8v+JVkm+OEkLPY=' 'sha256-XMzadgEgVSzUhb+Efa0YPeW7TiGXe4PVrZs5CANJquE='; script-src-elem 'self' 'unsafe-inline' https://www.google.com https://www.gstatic.com/; img-src 'self' data:; font-src 'self' data:; manifest-src 'self'; object-src 'none'; connect-src 'self'; frame-src https://www.youtube.com/ https://www.google.com/; child-src https://youtube.com;"
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
